package refind

import (
	"fmt"
	"os"
	"slices"
	"strings"

	"github.com/jmylchreest/refind-btrfs-snapshots/internal/btrfs"
	"github.com/jmylchreest/refind-btrfs-snapshots/internal/diff"
	"github.com/jmylchreest/refind-btrfs-snapshots/internal/kernel"
	"github.com/rs/zerolog/log"
)

// GenerateManagedConfigDiff generates a single managed config file with proper menuentry/submenu structure
func (g *Generator) GenerateManagedConfigDiff(sourceEntries []*MenuEntry, snapshots []*btrfs.Snapshot, rootFS *btrfs.Filesystem, configPath string) (*diff.FileDiff, error) {
	log.Debug().Int("entries", len(sourceEntries)).Int("snapshots", len(snapshots)).Msg("Generating managed config")

	var originalContent string
	var existingEntries map[string]*MenuEntry
	var isNewFile bool

	if existingFileContent, err := os.ReadFile(configPath); err == nil {
		originalContent = string(existingFileContent)
		existingEntries = g.parseExistingManagedConfig(originalContent)
		isNewFile = false
	} else {
		existingEntries = make(map[string]*MenuEntry)
		isNewFile = true
	}

	var content strings.Builder

	content.WriteString("# Generated by refind-btrfs-snapshots\n")
	content.WriteString("# WARNING - Submenu options will be overwritten automatically,\n")
	content.WriteString("# but menuentry attributes will be maintained.\n")
	content.WriteString("#\n")
	content.WriteString("# To enable snapshot booting, add this line to your refind.conf:\n")
	content.WriteString("#   include refind-btrfs-snapshots.conf\n")
	content.WriteString("#\n")

	if isNewFile {
		content.WriteString(g.generateTemplateEntry(sourceEntries, snapshots, rootFS))
	} else {
		content.WriteString("\n")
		content.WriteString(g.generateFromExistingEntries(existingEntries, snapshots, rootFS))
	}

	newContent := content.String()

	if newContent == originalContent {
		log.Debug().Str("path", configPath).Msg("File content matches, no changes required")
		return nil, nil
	}

	return &diff.FileDiff{
		Path:     configPath,
		Original: originalContent,
		Modified: newContent,
		IsNew:    originalContent == "",
	}, nil
}

// generateTemplateEntry creates a template entry for new files.
// When boot sets are available (from kernel.Scanner), generates one template
// per detected kernel with accurate paths. Falls back to hardcoded Arch defaults.
func (g *Generator) generateTemplateEntry(sourceEntries []*MenuEntry, snapshots []*btrfs.Snapshot, rootFS *btrfs.Filesystem) string {
	var content strings.Builder

	content.WriteString("\n")
	content.WriteString("# TEMPLATE ENTRY - Customize this example and remove the 'disabled' line to enable\n")
	content.WriteString("# You can create multiple menuentry blocks for different boot configurations\n")
	content.WriteString("\n")

	var sampleOptions string
	if len(sourceEntries) > 0 {
		sampleOptions = sourceEntries[0].Options
	}
	if sampleOptions == "" && rootFS != nil {
		if rootFS.UUID != "" {
			sampleOptions = fmt.Sprintf("quiet rw rootflags=subvol=@ root=UUID=%s", rootFS.UUID)
		} else {
			sampleOptions = "quiet rw rootflags=subvol=@"
		}
	}

	if len(g.bootSets) > 0 {
		for _, bs := range g.bootSets {
			if bs.Kernel == nil {
				continue
			}

			displayName := bs.DisplayName()
			content.WriteString(fmt.Sprintf("menuentry \"%s\" {\n", displayName))
			content.WriteString("    disabled\n")
			content.WriteString("    icon     /EFI/refind/icons/os_arch.png\n")
			content.WriteString(fmt.Sprintf("    loader   %s\n", bs.Kernel.Path))

			for _, mc := range bs.Microcode {
				content.WriteString(fmt.Sprintf("    initrd   %s\n", mc.Path))
			}
			if bs.Initramfs != nil {
				content.WriteString(fmt.Sprintf("    initrd   %s\n", bs.Initramfs.Path))
			}

			if sampleOptions != "" {
				content.WriteString(fmt.Sprintf("    options  %s\n", quoteRefindValue(sampleOptions)))
			}
			content.WriteString("    \n")
			content.WriteString("    # Snapshot submenus will be automatically generated below:\n")

			for i, snapshot := range snapshots {
				if i >= 2 {
					break
				}
				snapshotTitle := fmt.Sprintf("%s (%s)", displayName, g.getSnapshotDisplayName(snapshot))
				content.WriteString(fmt.Sprintf("    submenuentry \"%s\" {\n", snapshotTitle))
				if sampleOptions != "" {
					snapshotOptions := g.updateOptionsForSnapshot(sampleOptions, snapshot)
					content.WriteString(fmt.Sprintf("        options %s\n", quoteRefindValue(snapshotOptions)))
				}
				content.WriteString("    }\n")
			}

			content.WriteString("}\n")
			content.WriteString("\n")
		}
	} else {
		content.WriteString("menuentry \"Arch Linux\" {\n")
		content.WriteString("    disabled\n")
		content.WriteString("    icon     /EFI/refind/icons/os_arch.png\n")
		content.WriteString("    loader   /boot/vmlinuz-linux\n")
		content.WriteString("    initrd   /boot/initramfs-linux.img\n")
		if sampleOptions != "" {
			content.WriteString(fmt.Sprintf("    options  %s\n", quoteRefindValue(sampleOptions)))
		}
		content.WriteString("    \n")
		content.WriteString("    # Snapshot submenus will be automatically generated below:\n")

		for i, snapshot := range snapshots {
			if i >= 2 {
				break
			}
			snapshotTitle := fmt.Sprintf("Arch Linux (%s)", g.getSnapshotDisplayName(snapshot))
			content.WriteString(fmt.Sprintf("    submenuentry \"%s\" {\n", snapshotTitle))
			if sampleOptions != "" {
				snapshotOptions := g.updateOptionsForSnapshot(sampleOptions, snapshot)
				content.WriteString(fmt.Sprintf("        options %s\n", quoteRefindValue(snapshotOptions)))
			}
			content.WriteString("    }\n")
		}

		content.WriteString("}\n")
		content.WriteString("\n")
	}

	content.WriteString("# INSTRUCTIONS:\n")
	content.WriteString("# 1. Remove or comment out the 'disabled' line above to enable this entry\n")
	content.WriteString("# 2. Customize the title, icon, loader, and initrd paths for your system\n")
	content.WriteString("# 3. Adjust the options line to match your boot requirements\n")
	content.WriteString("# 4. Save the file and regenerate to see your customized menu with snapshots\n")
	content.WriteString("# 5. You can create multiple menuentry blocks for different configurations\n")

	return content.String()
}

// generateFromExistingEntries generates content from existing customized entries
func (g *Generator) generateFromExistingEntries(existingEntries map[string]*MenuEntry, snapshots []*btrfs.Snapshot, rootFS *btrfs.Filesystem) string {
	var content strings.Builder

	if len(existingEntries) == 0 {
		content.WriteString("# No customized menu entries found.\n")
		content.WriteString("# Please add menuentry blocks to this file or regenerate to create templates.\n")
		return content.String()
	}

	titles := make([]string, 0, len(existingEntries))
	for title := range existingEntries {
		titles = append(titles, title)
	}
	slices.Sort(titles)

	first := true
	for _, title := range titles {
		entry := existingEntries[title]
		if !first {
			content.WriteString("\n")
		}
		first = false

		entryContent := g.generateSingleMenuEntry(title, entry, snapshots, rootFS)
		content.WriteString(entryContent)
	}

	return content.String()
}

// getBootPlanForSnapshot looks up the first boot plan for a snapshot.
// Returns nil if no boot plans are available (falls back to ESP-mode behavior).
func (g *Generator) getBootPlanForSnapshot(snapshot *btrfs.Snapshot) *kernel.BootPlan {
	for _, plan := range g.bootPlans {
		if plan.Snapshot.Path == snapshot.Path {
			return plan
		}
	}
	return nil
}

// generateSingleMenuEntry generates a single menuentry with snapshots as submenus
func (g *Generator) generateSingleMenuEntry(title string, templateEntry *MenuEntry, snapshots []*btrfs.Snapshot, rootFS *btrfs.Filesystem) string {
	var content strings.Builder

	content.WriteString(fmt.Sprintf("menuentry \"%s\" {\n", title))

	if templateEntry.Icon != "" {
		content.WriteString(fmt.Sprintf("    icon %s\n", templateEntry.Icon))
	}
	if templateEntry.Volume != "" {
		content.WriteString(fmt.Sprintf("    volume %s\n", templateEntry.Volume))
	}
	if templateEntry.Loader != "" {
		content.WriteString(fmt.Sprintf("    loader %s\n", templateEntry.Loader))
	}
	for _, initrd := range templateEntry.Initrd {
		content.WriteString(fmt.Sprintf("    initrd %s\n", initrd))
	}
	if templateEntry.Options != "" {
		content.WriteString(fmt.Sprintf("    options %s\n", quoteRefindValue(templateEntry.Options)))
	}

	for _, snapshot := range snapshots {
		snapshotTitle := fmt.Sprintf("%s (%s)", title, g.getSnapshotDisplayName(snapshot))
		content.WriteString(fmt.Sprintf("    submenuentry \"%s\" {\n", snapshotTitle))

		plan := g.getBootPlanForSnapshot(snapshot)
		g.writeSplitSubmenuBody(&content, plan, templateEntry, snapshot)
		content.WriteString("    }\n")
	}

	content.WriteString("}\n")

	return content.String()
}

// writeSplitSubmenuBody handles both Split- and BLS-layout sets: rEFInd
// doesn't read BLS .conf files, so the emitted shape is identical.
func (g *Generator) writeSplitSubmenuBody(content *strings.Builder, plan *kernel.BootPlan, templateEntry *MenuEntry, snapshot *btrfs.Snapshot) {
	if plan != nil && plan.Mode == kernel.BootModeBtrfs {
		if plan.BtrfsVolume != "" {
			content.WriteString(fmt.Sprintf("        volume  %s\n", plan.BtrfsVolume))
		}
		content.WriteString(fmt.Sprintf("        loader  %s\n", plan.SnapshotKernel))
		for _, initrd := range plan.SnapshotInitrds {
			content.WriteString(fmt.Sprintf("        initrd  %s\n", initrd))
		}
	}

	snapshotOptions := g.updateOptionsForSnapshot(templateEntry.Options, snapshot)
	if snapshotOptions != "" {
		content.WriteString(fmt.Sprintf("        options %s\n", quoteRefindValue(snapshotOptions)))
	}
}
