package refind

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"

	"github.com/jmylchreest/refind-btrfs-snapshots/internal/btrfs"
	"github.com/jmylchreest/refind-btrfs-snapshots/internal/diff"
	"github.com/rs/zerolog/log"
)

// legacyTimestampPattern matches titles like "Some Title (2024-01-15_12-30-00)"
// from pre-marker generated entries, kept for backward-compat cleanup.
var legacyTimestampPattern = regexp.MustCompile(`^.+\s+\([^)]*\d{4}[^)]*\d{2}[^)]*\d{2}[^)]*\)$`)

// UpdateRefindLinuxConfWithAllEntries generates a diff for updating refind_linux.conf with all matching entries.
// When snapshots is empty, any previously generated marker section is cleaned up and the diff
// reflects only that cleanup (no new entries are written).
func (g *Generator) UpdateRefindLinuxConfWithAllEntries(snapshots []*btrfs.Snapshot, sourceEntries []*MenuEntry, rootFS *btrfs.Filesystem) (*diff.FileDiff, error) {
	if len(sourceEntries) == 0 {
		return nil, nil
	}

	linuxConfPath := sourceEntries[0].SourceFile
	for _, entry := range sourceEntries {
		if entry.SourceFile != linuxConfPath {
			return nil, fmt.Errorf("all entries must be from the same refind_linux.conf file")
		}
	}

	originalContent, err := os.ReadFile(linuxConfPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read refind_linux.conf: %w", err)
	}

	newContent, err := g.generateRefindLinuxConfWithAllEntries(string(originalContent), snapshots, sourceEntries, rootFS)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refind_linux.conf content: %w", err)
	}

	if newContent == string(originalContent) {
		log.Debug().Str("path", linuxConfPath).Msg("File content matches, no changes required")
		return nil, nil
	}

	return &diff.FileDiff{
		Path:     linuxConfPath,
		Original: string(originalContent),
		Modified: newContent,
		IsNew:    false,
	}, nil
}

// generateRefindLinuxConfWithAllEntries processes all entries and generates content with cleanup
func (g *Generator) generateRefindLinuxConfWithAllEntries(originalContent string, snapshots []*btrfs.Snapshot, sourceEntries []*MenuEntry, rootFS *btrfs.Filesystem) (string, error) {
	var lines []string
	var inGeneratedSection bool
	var foundMarkers bool

	markerScanner := bufio.NewScanner(strings.NewReader(originalContent))
	for markerScanner.Scan() {
		line := markerScanner.Text()
		if strings.Contains(line, "##refind-btrfs-snapshots-start") || strings.Contains(line, "##refind-btrfs-snapshots-end") {
			foundMarkers = true
			break
		}
	}

	scanner := bufio.NewScanner(strings.NewReader(originalContent))
	for scanner.Scan() {
		line := scanner.Text()

		if foundMarkers {
			if strings.Contains(line, "##refind-btrfs-snapshots-start") {
				inGeneratedSection = true
				continue
			}
			if strings.Contains(line, "##refind-btrfs-snapshots-end") {
				inGeneratedSection = false
				continue
			}

			if inGeneratedSection {
				continue
			}
		} else {
			if strings.Contains(line, "# Snapshot entries generated by refind-btrfs-snapshots") {
				inGeneratedSection = true
				continue
			}

			if inGeneratedSection {
				if strings.TrimSpace(line) != "" && g.isLegacyGeneratedSnapshotEntry(line) {
					continue
				} else if strings.TrimSpace(line) == "" {
					continue
				} else {
					inGeneratedSection = false
					lines = append(lines, line)
				}
			}
		}

		if !inGeneratedSection {
			lines = append(lines, line)
		}
	}

	if err := scanner.Err(); err != nil {
		return "", err
	}

	if len(sourceEntries) > 0 && len(snapshots) > 0 {
		if len(lines) > 0 && lines[len(lines)-1] != "" {
			lines = append(lines, "")
		}
		lines = append(lines, "##refind-btrfs-snapshots-start")

		for _, sourceEntry := range sourceEntries {
			for _, snapshot := range snapshots {
				snapshotTitle := fmt.Sprintf("%s (%s)", sourceEntry.Title, g.getSnapshotDisplayName(snapshot))
				snapshotOptions := g.updateOptionsForSnapshot(sourceEntry.Options, snapshot)

				snapshotLine := fmt.Sprintf("%s %s", quoteRefindValue(snapshotTitle), quoteRefindValue(snapshotOptions))
				lines = append(lines, snapshotLine)
			}
		}

		lines = append(lines, "##refind-btrfs-snapshots-end")
	}

	return strings.Join(lines, "\n") + "\n", nil
}

// isLegacyGeneratedSnapshotEntry checks if a line is a legacy generated snapshot entry.
// Used for backward compatibility when no markers are found.
func (g *Generator) isLegacyGeneratedSnapshotEntry(line string) bool {
	parts := g.parser.parseQuotedLine(strings.TrimSpace(line))
	if len(parts) < 1 {
		return false
	}

	title := parts[0]
	return legacyTimestampPattern.MatchString(title)
}
